// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: repeated.proto

package repeated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepeatedWithOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImplicitlyPacked        []int64 `protobuf:"varint,1,rep,packed,name=implicitly_packed,json=implicitlyPacked,proto3" json:"implicitly_packed,omitempty"`
	ExplicitlyPacked        []int64 `protobuf:"varint,2,rep,packed,name=explicitly_packed,json=explicitlyPacked,proto3" json:"explicitly_packed,omitempty"` // should same as default value
	ExplicitlyNotPacked     []int64 `protobuf:"varint,3,rep,name=explicitly_not_packed,json=explicitlyNotPacked,proto3" json:"explicitly_not_packed,omitempty"`
	ImplicitlyPackedOptions []int64 `protobuf:"varint,4,rep,packed,name=implicitly_packed_options,json=implicitlyPackedOptions,proto3" json:"implicitly_packed_options,omitempty"` // options should have no effect
}

func (x *RepeatedWithOptions) Reset() {
	*x = RepeatedWithOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repeated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedWithOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedWithOptions) ProtoMessage() {}

func (x *RepeatedWithOptions) ProtoReflect() protoreflect.Message {
	mi := &file_repeated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedWithOptions.ProtoReflect.Descriptor instead.
func (*RepeatedWithOptions) Descriptor() ([]byte, []int) {
	return file_repeated_proto_rawDescGZIP(), []int{0}
}

func (x *RepeatedWithOptions) GetImplicitlyPacked() []int64 {
	if x != nil {
		return x.ImplicitlyPacked
	}
	return nil
}

func (x *RepeatedWithOptions) GetExplicitlyPacked() []int64 {
	if x != nil {
		return x.ExplicitlyPacked
	}
	return nil
}

func (x *RepeatedWithOptions) GetExplicitlyNotPacked() []int64 {
	if x != nil {
		return x.ExplicitlyNotPacked
	}
	return nil
}

func (x *RepeatedWithOptions) GetImplicitlyPackedOptions() []int64 {
	if x != nil {
		return x.ImplicitlyPackedOptions
	}
	return nil
}

var File_repeated_proto protoreflect.FileDescriptor

var file_repeated_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0xeb, 0x01, 0x0a, 0x13, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79,
	0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x10, 0x69,
	0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x12,
	0x2f, 0x0a, 0x11, 0x65, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x42, 0x02, 0x10, 0x01, 0x52, 0x10,
	0x65, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x64,
	0x12, 0x36, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x5f, 0x6e,
	0x6f, 0x74, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x42,
	0x02, 0x10, 0x00, 0x52, 0x13, 0x65, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x4e,
	0x6f, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x19, 0x69, 0x6d, 0x70, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x42, 0x02, 0x30, 0x02, 0x52,
	0x17, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x6c, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0d, 0x48, 0x01, 0x5a, 0x09, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_repeated_proto_rawDescOnce sync.Once
	file_repeated_proto_rawDescData = file_repeated_proto_rawDesc
)

func file_repeated_proto_rawDescGZIP() []byte {
	file_repeated_proto_rawDescOnce.Do(func() {
		file_repeated_proto_rawDescData = protoimpl.X.CompressGZIP(file_repeated_proto_rawDescData)
	})
	return file_repeated_proto_rawDescData
}

var file_repeated_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_repeated_proto_goTypes = []interface{}{
	(*RepeatedWithOptions)(nil), // 0: repeated.RepeatedWithOptions
}
var file_repeated_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_repeated_proto_init() }
func file_repeated_proto_init() {
	if File_repeated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_repeated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedWithOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_repeated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repeated_proto_goTypes,
		DependencyIndexes: file_repeated_proto_depIdxs,
		MessageInfos:      file_repeated_proto_msgTypes,
	}.Build()
	File_repeated_proto = out.File
	file_repeated_proto_rawDesc = nil
	file_repeated_proto_goTypes = nil
	file_repeated_proto_depIdxs = nil
}
