/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: test/_/no_namespace/nested.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./double_nested";
import * as pb_1 from "google-protobuf";
export class Message extends pb_1.Message {
    #one_of_decls = [];
    constructor(data?: any[] | {
        fields?: dependency_1.MessageFields;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("fields" in data && data.fields != undefined) {
                this.fields = data.fields;
            }
        }
    }
    get fields() {
        return pb_1.Message.getWrapperField(this, dependency_1.MessageFields, 1) as dependency_1.MessageFields;
    }
    set fields(value: dependency_1.MessageFields) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    static fromObject(data: {
        fields?: ReturnType<typeof dependency_1.MessageFields.prototype.toObject>;
    }) {
        const message = new Message({});
        if (data.fields != null) {
            message.fields = dependency_1.MessageFields.fromObject(data.fields);
        }
        return message;
    }
    toObject() {
        const data: {
            fields?: ReturnType<typeof dependency_1.MessageFields.prototype.toObject>;
        } = {};
        if (this.fields != null) {
            data.fields = this.fields.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.fields !== undefined)
            writer.writeMessage(1, this.fields, () => this.fields.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Message {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Message();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.fields, () => message.fields = dependency_1.MessageFields.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Message {
        return Message.deserialize(bytes);
    }
}
