/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.17.0
 * source: test/_/optional/optional_proto3.proto
 * git: https://github.com/thesayyn/protoc-gen-ts
 *  */
import * as pb_1 from "google-protobuf";
export class NoNamespace extends pb_1.Message {
    constructor(data?: any[] | {
        should_not_be_required?: string[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("should_not_be_required" in data && data.should_not_be_required != undefined) {
                this.should_not_be_required = data.should_not_be_required;
            }
        }
    }
    get should_not_be_required() {
        return pb_1.Message.getField(this, 1) as string[];
    }
    set should_not_be_required(value: string[]) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        should_not_be_required?: string[];
    }) {
        const message = new NoNamespace({});
        if (data.should_not_be_required != null) {
            message.should_not_be_required = data.should_not_be_required;
        }
        return message;
    }
    toObject() {
        const data: {
            should_not_be_required?: string[];
        } = {};
        if (this.should_not_be_required != null) {
            data.should_not_be_required = this.should_not_be_required;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.should_not_be_required !== undefined)
            writer.writeRepeatedString(1, this.should_not_be_required);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): NoNamespace {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new NoNamespace();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): NoNamespace {
        return NoNamespace.deserialize(bytes);
    }
}
