/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: test/_/no_namespace/no_namespace.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class NoNamespace extends pb_1.Message {
    #one_of_decls = [];
    constructor(data?: any[] | {
        label?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("label" in data && data.label != undefined) {
                this.label = data.label;
            }
        }
    }
    get label() {
        return pb_1.Message.getField(this, 1) as string;
    }
    set label(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        label?: string;
    }) {
        const message = new NoNamespace({});
        if (data.label != null) {
            message.label = data.label;
        }
        return message;
    }
    toObject() {
        const data: {
            label?: string;
        } = {};
        if (this.label != null) {
            data.label = this.label;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (typeof this.label === "string" && this.label.length)
            writer.writeString(1, this.label);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): NoNamespace {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new NoNamespace();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.label = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): NoNamespace {
        return NoNamespace.deserialize(bytes);
    }
}
