/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: test/_/presence/presence_common.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum PresenceCommonEnum {
    ZERO = 0,
    ONE = 1,
    TWO = 2
}
export class PresenceCommonMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data?: PresenceCommonMessage.AsObjectPartial): PresenceCommonMessage {
        if (!data) {
            return new PresenceCommonMessage();
        }
        const message = new PresenceCommonMessage({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: PresenceCommonMessage.AsObject = {
            message: this.message
        };
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PresenceCommonMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PresenceCommonMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PresenceCommonMessage {
        return PresenceCommonMessage.deserialize(bytes);
    }
}
export namespace PresenceCommonMessage {
    export type AsObject = {
        message: string;
    };
    export type AsObjectPartial = {
        message?: string;
    };
}
export class PresenceCommonMessageOneOf extends pb_1.Message {
    #one_of_decls: number[][] = [[1, 2]];
    constructor(data?: any[] | ({} & (({
        int32?: number;
        message?: never;
    } | {
        int32?: never;
        message?: PresenceCommonMessage;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("int32" in data && data.int32 != undefined) {
                this.int32 = data.int32;
            }
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get int32() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set int32(value: number) {
        pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0]!, value);
    }
    get has_int32() {
        return pb_1.Message.getField(this, 1) != null;
    }
    clear_int32(): void {
        this.int32 = undefined!;
    }
    get message() {
        return pb_1.Message.getWrapperField(this, PresenceCommonMessage, 2) as PresenceCommonMessage | undefined;
    }
    set message(value: PresenceCommonMessage | undefined) {
        pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0]!, value);
    }
    get has_message() {
        return pb_1.Message.getField(this, 2) != null;
    }
    clear_message(): void {
        this.message = undefined!;
    }
    get oneof() {
        const cases: {
            [index: number]: "none" | "int32" | "message";
        } = {
            0: "none",
            1: "int32",
            2: "message"
        };
        return cases[pb_1.Message.computeOneofCase(this, [1, 2])]!;
    }
    static fromObject(data?: PresenceCommonMessageOneOf.AsObjectPartial): PresenceCommonMessageOneOf {
        if (!data) {
            return new PresenceCommonMessageOneOf();
        }
        const message = new PresenceCommonMessageOneOf({});
        if (data.int32 != null) {
            message.int32 = data.int32;
        }
        if (data.message != null) {
            message.message = PresenceCommonMessage.fromObject(data.message);
        }
        return message;
    }
    toObject() {
        const data: PresenceCommonMessageOneOf.AsObject = {
            int32: this.int32
        };
        if (this.message != null) {
            data.message = this.message.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_int32)
            writer.writeInt32(1, this.int32);
        if (this.has_message)
            writer.writeMessage(2, this.message, () => this.message!.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PresenceCommonMessageOneOf {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PresenceCommonMessageOneOf();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.int32 = reader.readInt32();
                    break;
                case 2:
                    reader.readMessage(message.message, () => message.message = PresenceCommonMessage.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PresenceCommonMessageOneOf {
        return PresenceCommonMessageOneOf.deserialize(bytes);
    }
}
export namespace PresenceCommonMessageOneOf {
    export type AsObject = {
        int32: number;
        message?: PresenceCommonMessage.AsObject;
    };
    export type AsObjectPartial = {
        int32?: number;
        message?: PresenceCommonMessage.AsObjectPartial;
    };
}
